{
 "title": "Cluster Utilization",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Avaliable cluster resources",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 2, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 1 },
       "type": "raw_document"
      }
     ],
     "query": "metadata.scope:cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Resources reserved by namespace quotas",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 11, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 1 },
       "type": "raw_document"
      }
     ],
     "query": "metadata.scope:cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "description": "Resources reserved by ResourceQuota's",
   "gridPos": { "h": 2, "w": 9, "x": 2, "y": 4 },
   "content": "### **Utilization - Cluster resources reserved by quota**"
  },
  {
   "type": "text",
   "description": "Resource usage of what's reserved by ResourceQuota's",
   "gridPos": { "h": 2, "w": 9, "x": 11, "y": 4 },
   "content": "### **Namespace utilization in relation to reserved by quota**"
  },
  {
   "title": "utilization.cpu",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "quota.utilization.cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metadata.namespace:NULL AND metadata.scope:cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "utilization.memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "quota.utilization.memory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metadata.namespace:NULL AND metadata.scope:cluster",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "quota.utilization.cpu",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "quota.utilization.cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metadata.namespace:NULL AND metadata.scope:namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "quota.utilization.memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "quota.utilization.memory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metadata.namespace:NULL AND metadata.scope:namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top namespace CPU utilization",
   "type": "table",
   "description": "Utilization of namespace CPU ResourceQuota",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "metadata.namespace.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "quota.utilization.cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "metadata.scope:namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top namespace MEM utilization",
   "type": "table",
   "description": "Utilization of namespace MEMORY ResourceQuota",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "metadata.namespace.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "3", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "quota.utilization.memory",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "metadata.scope:namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Bottom namespace CPU utilization",
   "type": "table",
   "description": "Utilization of namespace CPU ResourceQuota",
   "gridPos": { "h": 20, "w": 6, "x": 10, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "metadata.namespace.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "quota.utilization.cpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "quota.hard.cpu",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metadata.scope:namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Bottom namespace MEM utilization",
   "type": "table",
   "description": "Utilization of namespace MEMORY ResourceQuota",
   "gridPos": { "h": 20, "w": 6, "x": 16, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "metadata.namespace.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "3", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "quota.utilization.memory",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "quota.hard.memory",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metadata.scope:namespace",
     "timeField": "timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 }, "content": "\n" }
 ]
}